### ISSUE TITLE
currentPhaseId function returns 1 when the current phaseId is not equal to 1

### ISSUE THREAD

**Issue by seanroades** [smartcontractkit/feed-registry#12]
The feed registry contract (0x47Fb2585D2C56Fe188D0E6ec628a38b74fCeeeDf) is returning 1 incorrectly for the current phase id. For example, ETH/USD is currently at phaseId 5, but getCurrentPhaseId(base=ETH_Address, quote=USD_Address) returns 1.

**Comment by yosriady** [comment]
Hi @seanroades, thank you for opening an issue. 👍 

Feed proxies and the feed registry are both public interfaces to Chainlink's price feed aggregator contracts. They allow contract upgrades to be done without any changes required from end-users. Phase Ids are incremented whenever the underlying aggregator behind a feed proxy or a feed registry is updated. 

Phase Ids in the Chainlink Feed Registry and in the Price Feed Proxy contracts are independent of each other. [The ETH / USD proxy](https://etherscan.io/address/0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419) has a phaseId of 5, whereas the Feed registry entry for ETH / USD returns a phaseId of 1. This is expected, because the proxy has undergone more upgrades than the feed registry. 

I hope this helps to clarify.
